TraceError: Captured
    {
      "test": 5
    }
    TraceError: Test error
        Error: Test cause
        {
          "error": "test"
        }